version: '3'

networks:
  default:

services:
  jobsdev_webserver: 
    image: nginx:stable-alpine
    container_name: jobsdev_webserver
    ports: 
      - "7000:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - default

  jobsdev_app:
    build: 
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: jobsdev_app
    volumes: 
      - ./:/var/www/html
    ports: 
      - "9004:9004"
    networks: 
      - default  

  jobsdev_db:
    image: mysql:5.7.29
    container_name: jobsdev_db
    restart: unless-stopped
    tty: true
    ports: 
      - "3306:3306"
    environment: 
      MYSQL_DATABASE: jobsdev
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    networks: 
      - default
    volumes: 
      - ./docker/mysql:/var/lib/mysql 
  
  composer:
    image: composer:latest
    container_name: composer_laravel
    volumes: 
      - ./:/var/www/html
    working_dir: /var/www/html
    networks: 
      - default
  
  npm: 
    image: node:13.7
    container_name: npm_laravel
    volumes: 
      - ./:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['npm']

  artisan:
    build: 
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: artisan_laravel
    volumes: 
      - ./:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['php', '/var/www/html/artisan']
    networks: 
      - default